# Generated by Django 3.0.7 on 2020-09-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField(default=0)),
                ('headimage', models.ImageField(blank=True, upload_to='images')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField()),
                ('teaser', models.TextField(blank=True, verbose_name='teaser')),
            ],
        ),
    ]
